services:
  - type: static
    name: ia-msa-frn-agent
    buildCommand: npm install && npm run build
    publishPath: dist/baby-shower-frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
